## Assignment :- Breast Cancer dataset using 3 different models

### Load dataset

In [1]:
from sklearn.datasets import load_breast_cancer

In [2]:
breast_cancer = load_breast_cancer()

breast_cancer

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [4]:
breast_cancer.data.shape

(569, 30)

### Split data in training and testing

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(breast_cancer.data, breast_cancer.target, test_size=0.3, random_state=42)

### Scaling the data

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

### Logistic Regression

In [62]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

log_reg = LogisticRegression(C=0.1)
log_reg.fit(X_train_std, y_train)

prediction = log_reg.predict_proba(X_test_std)
prediction_int = prediction[ : , 1 ] > 0.5
prediction_int = prediction_int.astype(np.int)

accuracy_score(y_test, prediction_int)

C:\Users\shikhar.srivastava\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.9941520467836257

In [54]:
from sklearn.model_selection import cross_val_score

cross_val_score(log_reg, X_train_std, y_train, cv=8)

C:\Users\shikhar.srivastava\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\shikhar.srivastava\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\shikhar.srivastava\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\shikhar.srivastava\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\shikhar.srivastava\

array([0.98039216, 0.98      , 0.96      , 0.98      , 1.        ,
       0.95918367, 0.97959184, 0.95918367])

### SVM

In [30]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

lr_svc = LinearSVC(C=0.01)
lr_svc.fit(X_train_std, y_train)

prediction = lr_svc.predict(X_test_std)
# prediction_int = prediction[ : , 1 ] > 0.5
# prediction_int = prediction_int.astype(np.int)

accuracy_score(y_test, prediction)

0.9941520467836257

In [53]:
cross_val_score(lr_svc, X_train_std, y_train, cv=8)

array([0.98039216, 0.98      , 0.96      , 0.98      , 1.        ,
       0.95918367, 0.97959184, 0.97959184])

### KNN

In [43]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train_std, y_train)

prediction = knn.predict_proba(X_test_std)
prediction_int = prediction[ : , 1 ] > 0.5
prediction_int = prediction_int.astype(np.int)

accuracy_score(y_test, prediction_int)

0.9707602339181286

In [52]:
cross_val_score(knn, X_train_std, y_train, cv=8)

array([0.96078431, 0.96      , 0.96      , 0.98      , 0.98      ,
       0.93877551, 0.97959184, 0.93877551])

### Decision Tree Classifier

In [75]:
from sklearn.tree import DecisionTreeClassifier

dtree_clf = DecisionTreeClassifier(max_depth=3)
dtree_clf.fit(X_train_std, y_train)

prediction = dtree_clf.predict_proba(X_test_std)
prediction_int = prediction[ : , 1 ] > 0.5
prediction_int = prediction_int.astype(np.int)

accuracy_score(y_test, prediction_int)

0.9590643274853801

In [76]:
cross_val_score(dtree_clf, X_train_std, y_train, cv=8)

array([0.90196078, 0.94      , 0.88      , 0.92      , 0.94      ,
       0.91836735, 0.93877551, 0.93877551])

### RandomForest Classifier

In [84]:
from sklearn.ensemble import RandomForestClassifier

rdf_clf = RandomForestClassifier()
rdf_clf.fit(X_train_std, y_train)

prediction = rdf_clf.predict_proba(X_test_std)
prediction_int = prediction[ : , 1 ] > 0.5
prediction_int = prediction_int.astype(np.int)

accuracy_score(y_test, prediction_int)

C:\Users\shikhar.srivastava\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.9707602339181286